name: baseball-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.0
  - numpy>=1.24.3
  - pandas>=1.5.3
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.2
  - seaborn>=0.12.2
  - jupyterlab>=3.6.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pytest>=7.4.0
  - flask>=2.3.3
  - statsmodels>=0.14.0
  - scipy>=1.11.2
  - joblib>=1.3.1
  - requests>=2.31.0
  - beautifulsoup4>=4.12.2
  - pip:
    - mlflow>=2.6.0
    - shap>=0.42.1
    - scikit-optimize>=0.9.0
    - xgboost>=1.7.6
    - lightgbm>=4.0.0
    - catboost>=1.2.0
    - tensorflow>=2.13.0
    - streamlit>=1.25.0
    - google-cloud-storage>=2.10.0
    - functions-framework>=3.3.0